#!/bin/bash
#comment
echo "$1"
echo "$2"
echo "$3"
echo -n "MAX: "
if [ "$1" -ge "$2" -a "$1" -ge "$3" ]
then echo "$1"
else
	if [ "$2" -ge "$1" -a "$2" -ge "$3" ]
	then echo "$2"
	else echo "$3"
	fi
fi
