#!/bin/bash

trash=".trash"
log=".trash.log"

line=""
while read -r line; do	
	if  ! grep -q -F -- "$1" <<< "$line"; then
		continue
	fi

    file_path=$(echo "$line" | cut -d " " -f 1)
    link_name=$(echo "$line" | cut -d " " -f 2)
    echo "Was deleted with a link name: $link_name"

    echo "Are you sure to restore $file_path ? (y/n)"
    read -r answer < /dev/tty #read from terminal
    if [[ "$answer" == "y" ]]; then
        where_path="$file_path"
        if [[ ! -d "$(dirname "$where_path")" ]]; then
        	echo "No original directory. Restoring at home"
        	where_path="$HOME/$1"
        fi

        new_file_name="$1"
        while true; do
            dir_name=$(dirname "$where_path")
            where_path=$dir_name/$new_file_name
            if [[ -f "$where_path" ]]; then
                echo "File at this path ($where_path) already exists. Enter new file name:"
                new_file_name=""
                read -r new_file_name < /dev/tty
            else
                break
            fi
        done


    	ln "$HOME/$trash/$link_name" "$where_path" &&
        rm "$HOME/$trash/$link_name" && 
        {
      	    sed -i "/$link_name/d" "$HOME/$log"
            echo "Restored $file_path"
        }
    fi
done < "$HOME/$log"
