#!/bin/bash

prev_ppid=-1
sum=0
count=0

function calculateAvg() {
	if [[ "$count" -gt 0 ]]
	then
		avg=$(echo "scale=4; $sum / $count" | bc)
		echo "Average_Running_Children_of_ParentID=$prev_ppid is $avg"
	fi
}


input="output4.txt"
output="output5.txt"

while read -r line
do
	ppid=$(echo "$line" | awk -F'[:=]' '{print $4}')
	art=$(echo "$line" | awk -F'[:=]' '{print $6}')

	if [[ "$ppid" != "$prev_ppid" ]]
	then
		calculateAvg
		prev_ppid="$ppid"
		sum=0
		count=0
	fi

	sum=$(echo "scale=4; $sum + $art" | bc)
	count=$((count + 1))

	echo $line
done < $input > $output
calculateAvg >> $output
